name: Deploy to Digital Ocean with SSH Password

on:
  push:
    branches:
      - main

env:
  DROPLET_IP: 64.227.114.176

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Go environment
      uses: actions/setup-go@v2
      with:
        go-version: 1.21.1

    - name: Build
      run: go build -o go-cicd ./...

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install sshpass
      run: sudo apt-get update && sudo snap install doctl && sudo apt-get install -y sshpass

    - name: Authenticate with Digital Ocean
      run: doctl auth init --access-token ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }}

    - name: Deploy to Digital Ocean
      run: |
        export SSHPASS=${{ secrets.DROPLET_PASSWORD }}
        sshpass -e ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "pkill -f go-cicd || true"
        sshpass -e scp -o StrictHostKeyChecking=no ./go-cicd root@$DROPLET_IP:/root/
        sshpass -e ssh -o StrictHostKeyChecking=no root@$DROPLET_IP "nohup /root/golang/go-cicd &"
